export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_BOOKS = 'LOAD_BOOKS';
export const BOOKS_LOADED = 'BOOKS_LOADED';
export const SEARCH_BOOKS_LOADED = 'SEARCH_BOOKS_LOADED';
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const BOOK_SELECTED = 'BOOK_SELECTED';
export const BOOK_ADDED = 'BOOK_ADDED';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const TOGGLE_OPEN = "TOGGLE_OPEN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const RESET_BOOK_ADDED = "RESET_BOOK_ADDED";
export const HEADER_TOGGLE = "HEADER_TOGGLE";
export const HEADER_COLLAPSE = "HEADER_COLLAPSE";



